### ISSUE TITLE
[Live Site Bug] Registration HTTP Error 500

### ISSUE THREAD

**Issue by ajytan** [medhatelmasry/Project-Maestro#50]
After filling out the registration form and clicking the "_Sign Up_" button, the page loads for a long time and then results in an error.

**Screenshot of the Error:**
![image](https://user-images.githubusercontent.com/55104336/113631764-c8624200-961e-11eb-9160-5c9fd0a6cd80.png)

**Comment by chrisprosan** [comment]
Should be fixed by now
