### ISSUE TITLE
[Backend Bug & Improvement] "Add Students" page errors

### ISSUE THREAD

**Issue by Prerna0822** [medhatelmasry/Project-Maestro#91]
The following things must be improved in add_student_course.php :

1. Add a green success message after adding a student
2. Implement "_Back_" button
3. Fix navbar logo redirection (it should go back to the home page with the "_Create Course_" and "_View Courses_" buttons)

**Comment by Prerna0822** [comment]
Also the navbar logo is not redirecting to home page.

**Comment by ajytan** [comment]
Bug has been fixed and passed testing.
