### ISSUE TITLE
[Backend Bug] On "Create Projects" and "Project Details" pages, the navbar is redirecting all the way back to the "Index" page

### ISSUE THREAD

**Issue by ajytan** [medhatelmasry/Project-Maestro#97]
On the "_Create Projects_" and "Project Details" pages, the navbar is redirecting all the way back to the "_Index_" page.

It should just redirect back to the home page with the "_Create Course_" and "_View Courses_" buttons.

**Comment by ASingh368** [comment]
issue is fixed and tested
