### ISSUE TITLE
[Backend Bug] Able to access all pages (except for the home.php page) by changing the URL

### ISSUE THREAD

**Issue by ajytan** [medhatelmasry/Project-Maestro#98]
Any is able to access all the pages (except for the home.php page) by changing the URL.

We should be checking if a user is logged in on every single page so that unauthorized users can't access the site.

**Comment by chrisprosan** [comment]
fixed for create_project_outline and view_projects

**Comment by ASingh368** [comment]
issue is fixed and tested
